### ISSUE TITLE
ImportError: No module named 'docopt'

### ISSUE THREAD

**Issue by IonicaBizau** [barrucadu/markov#12]
Any idea why I'm getting `ImportError: No module named 'docopt'`, on Ubuntu 16.10?

**Comment by barrucadu** [comment]
Yes, it uses docopt to parse input in the repl (which is perhaps not the best way, but it's how it is...).  You can install it with pip: https://github.com/barrucadu/markov#getting-started

**Comment by IonicaBizau** [comment]
@barrucadu I did follow the exact instructions and everything worked well. I also did `pip install docopt` manually, and it still shows that error...

**Comment by barrucadu** [comment]
Then I'm afraid I don't know, the virtualenv should put the module into scope
