### ISSUE TITLE
Using as a module?

### ISSUE THREAD

**Issue by aendrew** [barrucadu/markov#6]
Hi!
First off — so rad. And I dig the Tumblog so much; kudos!

I'm wanting to do an art project with Markov chains and newspaper headlines, and have written a Python app to collect stuff into a NoSQL database. Any suggestions how I'd go about importing this as a submodule and using its functionality in my project?

Thanks!

**Comment by darrenpmeyer** [comment]
Check out [this commit](https://github.com/barrucadu/markov/commit/66b6ce4118800c3ae175f710666d05a52381e900) -- should solve your issue.
