### ISSUE TITLE
corpus not found

### ISSUE THREAD

**Issue by djogopatrao** [barrucadu/markov#7]
the wget command specified on README.md won't work; why not add it to the github repository?

djogo@infomed01:~/Downloads/markov-master$ wget http://misc.barrucadu.co.uk/pub/KingJamesProgramming.tar.xz
--2015-01-20 11:24:06--  http://misc.barrucadu.co.uk/pub/KingJamesProgramming.tar.xz
Resolving misc.barrucadu.co.uk (misc.barrucadu.co.uk)... 213.138.101.68, 2001:41c8:51:144:feff:ff:fe00:e08
Connecting to misc.barrucadu.co.uk (misc.barrucadu.co.uk)|213.138.101.68|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-01-20 11:24:07 ERROR 404: Not Found.

**Comment by nishantmodak** [comment]
+1 

What is the corpus location?
